---
- name: Copy backend artifact
  copy:
    src: ~/artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: Extract backend
  become : yes
  shell: |
    tar -vxf artifact.tar.gz
    rm -f artifact.tar.gz

- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
