---
- name: Extract backend
  ansible.builtin.unarchive:
    src: ../../artifact.tar.gz
    dest: ~/


- name: Executing node
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start